server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: dummy-api
          uri: http://localhost:8080
          predicates:
            - Path=/api/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**, /swagger-ui/**, /v3/api-docs/**
          filters:
            - JwtAuth

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - JwtAuth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
